### PR TITLE
Add mock files to `vts/policymanager`

### LINKED ISSUE #32: BUG: Missing mocks under services/vts/policymanager
Mocks under services/vts/policymanager needs to be submitted for command `go mod tidy` to execute correctly.

Issue linked to #24

### PR DESCRIPTION
**Pull request by yogeshbdeshpande**
add missing mock files to `vts/policymanager`

### CODE REVIEW

**Comment by thomas-fossati** [comment]
> Include `vts/policymanager` unit tests and submit the generated mock files

There are no unit tests here AFAICS.

**Review by thomas-fossati — APPROVED** [review]

**Comment by thomas-fossati** [comment]
we need to add an issue to track hooking policy manager unit testing into the main build

**Comment by yogeshbdeshpande** [comment]
> we need to add an issue to track hooking policy manager unit testing into the main build

Yes doing this now!

**Comment by yogeshbdeshpande** [comment]
> > we need to add an issue to track hooking policy manager unit testing into the main build
> 
> Yes doing this now!

Issue #34 raised.

**Pull request merged**
